import type { RankingsData } from "../types";

/** Load pre-computed rankings generated by scripts/build_rankings.py. */
export async function loadRankings(): Promise<RankingsData> {
  const url = `${import.meta.env.BASE_URL}data/rankings.json`;
  const res = await fetch(url, { cache: "no-store" });
  if (!res.ok) {
    throw new Error(`Failed to load rankings (${res.status}). Run "npm run predev" or check GitHub Actions output.`);
  }
  const data = (await res.json()) as RankingsData;
  if (!data || typeof data !== "object" || !data.channels) {
    throw new Error("rankings.json has an unexpected shape.");
  }
  return data;
}
